FROM node:18-alpine

# Create app directory
WORKDIR /app

# Install nodemon globally
RUN npm install -g nodemon

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

EXPOSE 5001

CMD ["npm", "start"]
